services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/postgresql/data
      # ボリュームマウント
  web:
    build: .
    # 同じ階層にあるDockerfileを使う
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
      # バインドマウント
volumes:
  db-data: