services:
  web:
    # Dockerfileをもとにコンテナを作成したい場合はbuild
    # Dockerfileまでのパスを記述する(今回はyamlと同じ階層なので".")
    build: .
    environment:
      # たぶん開発者モード
      FLASK_ENV: developement
    ports:
      - "5000:5000"
    volumes:
        # バインドマウント
      - ./src:/usr/src/app